ALTER TABLE carts MODIFY user_id BIGINT UNSIGNED NULL;
ALTER TABLE carts ADD COLUMN guest_token VARCHAR(100) NULL UNIQUE AFTER user_id;

ALTER TABLE orders DROP FOREIGN KEY orders_ibfk_1;
ALTER TABLE orders MODIFY user_id BIGINT UNSIGNED NULL;
ALTER TABLE orders ADD COLUMN email VARCHAR(255) NULL AFTER user_id;
ALTER TABLE orders ADD CONSTRAINT orders_user_id_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL;
