ALTER TABLE users ADD COLUMN google_subject VARCHAR(255) NULL UNIQUE AFTER password_hash;

CREATE TABLE google_auth_codes (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  code CHAR(64) NOT NULL UNIQUE,
  user_id BIGINT UNSIGNED NOT NULL,
  expires_at DATETIME NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX (expires_at)
);
